version: '3'

services:
  flask:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: flask-server
    working_dir: /app/
    ports:
      - 5000:5000
    volumes:
      - ./server/:/app/
    tty: true
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/app
    command: sh -c "yarn start"
    ports:
      - "3000:3000"
    volumes:
      - ./server/:/app/
      - ./frontend/:/usr/app/
    tty: true