version: '3'

services:
  flask:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: flask-server
    working_dir: /app/
    ports:
      - 5000:5000
    volumes:
      - ./server/app/:/app/
    tty: true
    environment:
      FLASK_ENV: 'development'
      FLASK_APP: 'app.py'
    command: flask run -h 0.0.0.0
  mysql:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jukukurudb
      MYSQL_USER: eijitoriki
      MYSQL_PASSWORD: root
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./server/db/data:/var/lib/mysql
      - ./server/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./frontend:/usr/app
  #   command: sh -c "yarn start"
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./server/:/app/
  #     - ./frontend/:/usr/app/
  #   tty: true