"""empty message

Revision ID: a593c55020df
Revises: 263d8cdac0a3
Create Date: 2022-07-20 13:22:02.365125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a593c55020df'
down_revision = '263d8cdac0a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comingdates',
    sa.Column('dateId', sa.Integer(), nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.Column('isComeKoma1', sa.Boolean(), nullable=False),
    sa.Column('isComeKoma2', sa.Boolean(), nullable=False),
    sa.Column('isComeKoma3', sa.Boolean(), nullable=False),
    sa.Column('isComeKoma4', sa.Boolean(), nullable=False),
    sa.Column('isComeKoma5', sa.Boolean(), nullable=False),
    sa.Column('isComeKoma6', sa.Boolean(), nullable=False),
    sa.Column('isComeKoma7', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('dateId', 'studentId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comingdates')
    # ### end Alembic commands ###
